name: CD Pipeline - Jobs

on:

  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

  workflow_dispatch:

    inputs:

      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod

      run_post_deployment:
        description: 'Run Post Deployment'
        required: true
        default: true
        type: boolean

      post_deployment_check:
        description: 'Use -b'
        required: true
        default: true
        type: boolean

jobs:

###################################################
# DEV DEPLOY
###################################################

  dev_deploy:
    if: |
      github.event_name == 'workflow_run' ||
      (github.event_name == 'workflow_dispatch' &&
      github.event.inputs.environment == 'dev')

    name: DEV Deploy
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Deploy DEV
        run: |
          echo "Deploying to DEV"

  dev_post_deploy:
    needs: dev_deploy

    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.environment == 'dev' &&
      github.event.inputs.run_post_deployment == 'true'

    name: DEV Post Deploy
    runs-on: ubuntu-latest
    environment: DEV

    steps:

      - name: DEV Post Deployment
        run: |

          if [ "${{ github.event.inputs.post_deployment_check }}" = "true" ]; then
            echo "Running DEV Post Deployment WITH -b"
          else
            echo "Running DEV Post Deployment WITHOUT -b"
          fi

###################################################
# QA DEPLOY
###################################################

  qa_deploy:
    if: github.event.inputs.environment == 'qa'

    name: QA Deploy
    runs-on: ubuntu-latest
    environment: QA

    steps:
      - name: Deploy QA
        run: |
          echo "Deploying to QA"

  qa_post_deploy:
    needs: qa_deploy

    if: |
      github.event.inputs.environment == 'qa' &&
      github.event.inputs.run_post_deployment == 'true'

    name: QA Post Deploy
    runs-on: ubuntu-latest
    environment: QA

    steps:

      - name: QA Post Deployment
        run: |

          if [ "${{ github.event.inputs.post_deployment_check }}" = "true" ]; then
            echo "Running QA Post Deployment WITH -b"
          else
            echo "Running QA Post Deployment WITHOUT -b"
          fi

###################################################
# UAT DEPLOY
###################################################

  uat_deploy:
    if: github.event.inputs.environment == 'uat'

    name: UAT Deploy
    runs-on: ubuntu-latest
    environment: UAT

    steps:
      - name: Deploy UAT
        run: |
          echo "Deploying to UAT"

  uat_post_deploy:
    needs: uat_deploy

    if: |
      github.event.inputs.environment == 'uat' &&
      github.event.inputs.run_post_deployment == 'true'

    name: UAT Post Deploy
    runs-on: ubuntu-latest
    environment: UAT

    steps:

      - name: UAT Post Deployment
        run: |

          if [ "${{ github.event.inputs.post_deployment_check }}" = "true" ]; then
            echo "Running UAT Post Deployment WITH -b"
          else
            echo "Running UAT Post Deployment WITHOUT -b"
          fi

###################################################
# PROD DEPLOY
###################################################

  prod_deploy:
    if: github.event.inputs.environment == 'prod'

    name: PROD Deploy
    runs-on: ubuntu-latest
    environment: PROD

    steps:
      - name: Deploy PROD
        run: |
          echo "Deploying to PROD"

  prod_post_deploy:
    needs: prod_deploy

    if: |
      github.event.inputs.environment == 'prod' &&
      github.event.inputs.run_post_deployment == 'true'

    name: PROD Post Deploy
    runs-on: ubuntu-latest
    environment: PROD

    steps:

      - name: PROD Post Deployment
        run: |

          if [ "${{ github.event.inputs.post_deployment_check }}" = "true" ]; then
            echo "Running PROD Post Deployment WITH -b"
          else
            echo "Running PROD Post Deployment WITHOUT -b"
          fi
