name: CD Pipeline

on:
  workflow_dispatch:

    inputs:

      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - qa
          - uat
          - prod

      run_post_deployment:
        description: 'Run Post Deployment'
        required: true
        default: true
        type: boolean

      post_deployment_check:
        description: 'Enable post deployment'
        required: true
        default: true
        type: boolean

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Deploy
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}"

  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy

    if: github.event.inputs.run_post_deployment == 'true'

    steps:

      - name: Post Deployment
        run: |

          if [ "${{ github.event.inputs.post_deployment_check }}" = "true" ]; then
            echo "Running with -b"
          else
            echo "Running without -b"
          fi
