name: CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  workflows: write   # allows triggering another workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Building application"

      - name: Trigger DEV CD
        run: |
          gh workflow run CD-job.yaml \
          -f environment="dev" \
          -f image="1.0.${{ github.run_number }}" \
          -f run_post_deployment="false" \
          -f post_deployment_check="true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
