name: Rerun-Aware-Demo

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:

  history-check:
    name: HISTORY CHECK

    runs-on: ubuntu-latest

    outputs:
      run_post_deployment: ${{ steps.check.outputs.run_post_deployment }}

    steps:
      - name: Check previous rerun attempt jobs
        id: check
        run: |

          echo "Checking rerun workflow history..."

          # Default value
          run_post_deployment=true

          echo "Current Run Attempt: ${{ github.run_attempt }}"

          # FIRST EXECUTION
          if [ "${{ github.run_attempt }}" -eq 1 ]; then

            echo "First workflow execution"

            echo "run_post_deployment=true" >> $GITHUB_OUTPUT

            exit 0
          fi

          echo "Rerun detected"

          # Previous attempt
          previous_attempt=$((${{ github.run_attempt }} - 1))

          echo "Previous Attempt: $previous_attempt"

          # Fetch jobs from previous attempt of SAME RUN
          jobs=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/$previous_attempt/jobs")

          echo "$jobs"

          deployment_status=$(echo "$jobs" | jq -r \
            '.jobs[] | select(.name=="Deployment") | .conclusion')

          post_deployment_status=$(echo "$jobs" | jq -r \
            '.jobs[] | select(.name=="Post Deployment") | .conclusion')

          echo "Previous Deployment Status: $deployment_status"
          echo "Previous Post Deployment Status: $post_deployment_status"

          # Skip post deployment if BOTH jobs already succeeded
          if [[ "$deployment_status" == "success" && "$post_deployment_status" == "success" ]]; then

            echo "Deployment and Post Deployment already succeeded previously"

            run_post_deployment=false
          fi

          echo ""
          echo "Final Decision"
          echo "Run Post Deployment: $run_post_deployment"

          echo "run_post_deployment=$run_post_deployment" >> $GITHUB_OUTPUT

  deployment:
    name: Deployment

    runs-on: ubuntu-latest

    needs: history-check

    # ALWAYS RUN
    steps:
      - run: |
          echo "Running Deployment"

  post-deployment:
    name: Post Deployment

    runs-on: ubuntu-latest

    needs:
      - history-check
      - deployment

    # SKIP IF ALREADY SUCCESSFUL IN PREVIOUS ATTEMPT
    if: needs.history-check.outputs.run_post_deployment == 'true'

    steps:
      - run: |
          echo "Running Post Deployment"

          # Uncomment for testing
          # exit 1

  final-job:
    name: FINAL JOB

    runs-on: ubuntu-latest

    needs:
      - history-check
      - deployment
      - post-deployment

    if: always()

    steps:
      - run: |

          echo "================================="
          echo "Run Attempt : ${{ github.run_attempt }}"
          echo "Deployment RESULT      : ${{ needs.deployment.result }}"
          echo "Post Deployment RESULT : ${{ needs.post-deployment.result }}"
          echo "================================="
