name: Rerun-Recovery-Demo

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:

  history-check:
    name: HISTORY CHECK

    runs-on: ubuntu-latest

    outputs:
      run_jobB: ${{ steps.check.outputs.run_jobB }}

    steps:
      - name: Check all previous rerun attempts
        id: check
        run: |

          echo "Checking rerun workflow history..."

          run_jobB=true

          current_attempt=${{ github.run_attempt }}

          echo "Current Attempt: $current_attempt"

          # FIRST EXECUTION
          if [ "$current_attempt" -eq 1 ]; then

            echo "First workflow execution"

            echo "run_jobB=true" >> $GITHUB_OUTPUT

            exit 0
          fi

          echo "Scanning ALL previous attempts..."

          # LOOP ALL PREVIOUS ATTEMPTS
          for (( attempt=1; attempt<current_attempt; attempt++ ))
          do

            echo ""
            echo "Checking Attempt: $attempt"

            jobs=$(curl -s \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/$attempt/jobs")

            jobA_status=$(echo "$jobs" | jq -r \
              '.jobs[] | select(.name=="JOB A") | .conclusion')

            jobB_status=$(echo "$jobs" | jq -r \
              '.jobs[] | select(.name=="JOB B") | .conclusion')

            echo "JOB A Status: $jobA_status"
            echo "JOB B Status: $jobB_status"

            # IF JOB B EVER SUCCEEDED
            if [[ "$jobA_status" == "success" && "$jobB_status" == "success" ]]; then

              echo ""
              echo "Historical successful state found"
              echo "Skipping JOB B"

              run_jobB=false

              break
            fi
          done

          echo ""
          echo "Final Decision"
          echo "Run JOB B: $run_jobB"

          echo "run_jobB=$run_jobB" >> $GITHUB_OUTPUT

  jobA:
    name: JOB A

    runs-on: ubuntu-latest

    needs: history-check

    # ALWAYS RUN
    steps:
      - run: |
          echo "Running JOB A"

  jobB:
    name: JOB B

    runs-on: ubuntu-latest

    needs:
      - history-check
      - jobA

    # SKIP IF ALREADY SUCCESSFUL IN ANY OLD ATTEMPT
    if: needs.history-check.outputs.run_jobB == 'true'

    steps:
      - run: |
          echo "Running JOB B"

          # Uncomment for testing
          # exit 1

  final-job:
    name: FINAL JOB

    runs-on: ubuntu-latest

    needs:
      - history-check
      - jobA
      - jobB

    if: always()

    steps:
      - run: |

          echo "================================="
          echo "Run Attempt : ${{ github.run_attempt }}"
          echo "JOB A RESULT : ${{ needs.jobA.result }}"
          echo "JOB B RESULT : ${{ needs.jobB.result }}"
          echo "================================="
